# Sherlock Mystery

Solve a series of mysteries as described below. To solve these you must integrate all of the skills you have learned in this class.

If you decide to make a separate notebook or python script(s) for each question, then name them with the appropriate prefix (e.g., q1). You may find it useful to write a utilities file with some common functions or variables you may want to reuse throughout the assignment, as we have done with the `utils.py` file released with each assignment. You should then commit these files along with this notebook to document your answers. You may also want to save intermediate data throughout this process; feel free to do so and note where you do this in your code.

You must answer all 4 questions. Your score out of 30 points will depend on the following criteria:

>**Answer** (6 points, 2 points each for Q2, Q3, Q4): Did you get the right answer?  
>**Approach** (16 points, 4 points for each question): Does the code reproduce your answer and was your approach sound, innovative, and efficient?  
>**Clarity** (8 points, 2 points for each question): Is the code readable, clearly commented, and well-structured?

**Due Date:** The final project is due back on **May 3 at 11:59pm**. Whatever is committed to your assignment repo at that time will be submitted automatically. If you complete the assignment early, please Slack us so we can begin grading. Final grades are due in some cases within 48 hours, so late submissions will not be accepted.

You should think about your final submission as a "tutorial" for somebody learning these techniques. The quality and clarity of your code should meet the standard of being published publicly. Integrate all the best coding practices you have learned in this course in completing these assignments. 

Science is a collective enterprise and thus you are welcome to talk with your peers. However, you must write your own code, provide your own explanations and comments, and generate your final answers on your own.

<div class="alert alert-block alert-warning">

<strong>Important:</strong> The dataset we are using has been published in several articles, meaning that there are ways to find or verify some of the answers by looking at published data and labels. Although we encourage you to read these papers, please only look at the data and labels provided on Grace. Any evidence of doing otherwise, including providing an answer without code that can re-generate it from the data/labels we provided, will result in a score of zero.
</div>

When committing files to github, make sure you do not commit any of the data or results you generate. These can get prohibitively large and make it hard for you to use git. To avoid this, **only upload notebooks and scripts**.

## Dataset

Participants watched an episode of BBC's Sherlock in two parts during fMRI. You may watch the parts in the links below, but do not save, post, or share these copyrighted files:

Part 1: https://1drv.ms/v/s!Aobi2ryypFQCgpZ4UTJfrzPgJBO1jw

Part 2: https://1drv.ms/v/s!Aobi2ryypFQCgpoabssIiGezcNL1zA

The length of the scans are (after 20 TRs were cropped from beginning):

> Part 1: 946 TRs  
> Part 2: 1030 TRs

For the questions below, we will provide you with the full data (scans and labels) from Part 1 and partial data from Part 2.

All of these data are stored here: `/gpfs/gibbs/project/cmhn/data/Sherlock_processed/`

**Data:** Data for all subjects, part 1, are stored in the `part_1` directory. Partial data specific to questions 2, 3, & 4 are explained with their respective questions. 

**Masks:** We have provided the following masks that *may* be useful to you, stored in the `masks` directory:
> `pmc_nn`: posterior medial cortex(functionally implicated in tasks as diverse as attention, memory, spatial navigation, emotion, self-relevance detection, and reward evaluation.)

> `ddmn_mpfc`: medial pre-frontal cortex(attention, inhibitory control, habit formation and working, spatial or long-term memory)

> `aud_early`: early auditory cortex  
> `a1_rev`: the first auditory area  
> `early_visual`: early visual cortex  

> `intersect_mask`: whole-brain mask of voxels common to all subjects  
> `MNI152_T1_3mm_brain_mask`: reference MNI mask

**Regressor information:** The regressor_file.csv contains extremely useful and detailed information for describing and labeling *both* parts of the movie.

<div class="alert alert-block alert-info">

<strong>Important:</strong> These TRs have already been shifted to align the peak HRF with the labels (i.e., the label for time point *t* corresponds to TR *t* in the processed data).
</div>



## 1. Classification

Using the regressor file, build classifiers of movie content (e.g., is the scene indoor or outdoor, is Sherlock present on the screen, and many other options). Without double-dipping or overfitting, you should aim to get the highest classification accuracy possible, using the training sample of data (Part 1). It is up to you to choose how to use/group the labels, what mask to use, etc.

In your answer, you should present three distinct classifiers, **each focusing on a different regressor**, that yield promising results (i.e., where you think the classifier is actually picking up some signal). **Importantly, this question will be graded purely for approach and clarity, not for accuracy or performance**. You should be motivated to come up with classifiers that are actually useful, because you will need accurate classifiers to decode the mystery segment in Question 3. You are welcome to include more than three classifiers in your answer, but if so, you should tell us which of the three you would like us to grade. 

Some important notes: 

1) Keep in mind that nearby TRs are highly correlated; as such, methods like StratifiedShuffleSplit that can assign adjacent TRs to training and test sets are effectively double-dipping, so you should avoid using these methods.

2) If the labels are not balanced (within and across folds), this can bias results; for example, if 99% of the TRs have a label of 1 and 1% have a value of 0, then the classifier can achieve 99% accuracy simply by guessing “1” all of the time. For this reason, you should strive to have the labels be relatively balanced. However, in real-world data, this can be difficult or impossible to achieve; it is OK to run unbalanced analyses, but keep the unbalanced nature of the labels in mind when you are assessing how good performance is for a particular classifier, or you can create functions to balance the labels during training.

3) Keep in mind that you can transform the regressors to improve balance. e.g., the “arousal” regressor has 5 levels, but you can binarize it so that it has two roughly-equally-balanced groups instead of 5 imbalanced groups.

4) If you find a particularly good approach, we encourage you to share a verbal description of the approach on Slack so others can build on your idea. Just make sure that you only share a verbal description of the approach and not the actual code. And if you read about a cool approach on Slack, feel free to try variants of that approach for your own work - that is completely allowed.


**Data directory:** `/gpfs/gibbs/project/cmhn/data/Sherlock_processed/part_1/`


### Summarize your approach to classification
What three different regressors did you choose for your classifier? What kind of data did you use as input to the classifier? What classifier parameters did you use and why?

**Answer:**  
  
I chose the regressors indoor/outdoor scene, valence, and arousal as I assumed that there would be distinct masks which would be most useful in predicting each respectively. I performed an analysis where I used every available mask to predict every regressor and thus identified the masks that had the highest accuracy in predicting each regressor.  
  
the best mask for predicting Indoor/Outdoor Scenes is the visual mask with an accuracy of 0.637, with chance being 0.5

the best mask for predicting Valence is tied between a1_maskedData, pmc_maskedData, and visual_maskedData all at accuracy = 0.865

the best mask for predicting Arousal is the whole brain mask with an accuracy of 0.61, with chance being 0.5, however since the accuracy is low and this is a large mask that takes very long to run in a classifier, we can utilize the much smaller early auditory cortex (aud) mask for further optimization, which had an accuracy of 0.591.  
  
I used classifier parameters C = 0.01, gamma = 0.01, kernel = 'linear' for the aforementioned analyses and for the indoor/outdoor classifier and valence classifier as both of those had satisfactory above chance accuracy.

I wanted to improve the accuracy of Arousal to be above 0.60 and there I utilized GridSearchCV and SelectKBest to determine that selecting for the k = 280 best features with the classifier parameters set to C = 0.1, gamma = 0.01, and kernel = 'rbf', the arousal classifier accuracy improved from 0.591 to 0.635.

### Include your code below 
Please make sure that your code is commented. If you performed analyses outside of this notebook (e.g., in a python script that needed more computational resources) please note that here and be sure to upload any accompanying notebook(s) or script(s) (submissions without accompanying code will be given zero points).

In [1]:
#load necessary libraries
import os
import pandas as pd
from brainiak import image, io
from nilearn.maskers import NiftiMasker
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
%matplotlib inline
from brainiak import image, io
from scipy.stats import stats
import nibabel as nib
import numpy as np
from matplotlib import pyplot as plt
from sklearn.model_selection import GridSearchCV, PredefinedSplit, StratifiedKFold
from sklearn.svm import SVC
from finUtils import processregressor, remove_duplicate_rows, upsample_labels, mask_preprocess_data
from sklearn.feature_selection import SelectKBest, f_classif

os.listdir('/gpfs/gibbs/project/cmhn/data/Sherlock_processed/masks')

['pmc_nn.nii',
 'intersect_mask.nii.gz',
 'early_visual.nii',
 'ddmn_mpfc.nii',
 'a1_rev.nii',
 'MNI152_T1_3mm_brain_mask.nii',
 'aud_early.nii']

In [2]:
#establish data directory
data_dir ='/gpfs/gibbs/project/cmhn/data/Sherlock_processed/'

# declare and display the regressors data
df = pd.read_csv(data_dir + 'regressor_file.csv') # pandas plays best with csv files
df.head(200)

Segment Number    Scene Title   Start Time (s)    End Time (s)   \
0               1.0  Cartoon Intro               0.0            12.0   
1               2.0             NaN             12.0            15.0   
2               3.0             NaN             15.0            17.0   
3               4.0             NaN             17.0            23.0   
4               5.0             NaN             23.0            29.0   
..              ...             ...              ...             ...   
195           196.0             NaN            620.0           621.0   
196           197.0             NaN            621.0           622.0   
197           198.0             NaN            622.0           625.0   
198           199.0             NaN            625.0           628.0   
199           200.0             NaN            628.0           630.0   

     Start TR                           Scene Details - A Level   \
0         0.0  People in popcorn, candy, and soft drink costu...   
1         8.0  Popcorn is being popped in a large popcorn mac...   
2        10.0    Men sing in reply: "the popcorn can't be beat!"   
3        11.0  A family of four, a father with a black suit, ...   
4        15.0  A view of the lobby with a display of snacks f...   
..        ...                                                ...   
195     413.0  Mike: "Sorry, it's in my coat." and walks to h...   
196     414.0  Sherlock doesn't answer and peers down at his ...   
197     415.0  John says: "Umm here" Sherlock turns his head ...   
198     417.0  Sherlock says: "Oh, thank you." (unexpectedly ...   
199     419.0  Mike says pointing at John: "He's an old frien...   

                               Scene Details - B Level  \
0    1. Cartoon introduction - singers repeat "Let'...   
1                                          Segment 1-7   
2                                                        
3                                                        
4                                                        
..                                                 ...   
195                                                      
196                                                      
197                                                      
198                                                      
199                                                      

    Original B Levels (Janice) fixed Space-In/Outdoor Who-N/G/M  ...  \
0                         1. Cartoon           Indoor         G  ...   
1                                NaN           Indoor         G  ...   
2                                NaN           Indoor         G  ...   
3                                NaN           Indoor         G  ...   
4                                NaN           Indoor         G  ...   
..                               ...              ...       ...  ...   
195                              NaN           Indoor         G  ...   
196                              NaN           Indoor         M  ...   
197                              NaN           Indoor         M  ...   
198                              NaN           Indoor         M  ...   
199                              NaN           Indoor         G  ...   

                    Name - Focus              Name - Speaking  \
0    Cartoon People in Costumes   Cartoon People in Costumes    
1                            NaN                Female Singer   
2                            NaN                 Male Singers   
3                            NaN           Background Singers   
4                  Cartoon Woman           Background Singers   
..                           ...                          ...   
195                         Mike                         Mike   
196                     Sherlock                          NaN   
197               Sherlock, John                         John   
198                     Sherlock                     Sherlock   
199                         Mike              

In [3]:
#declare constants for part 1
num_subs = 17
subs = np.arange(num_subs)
numTRs = 946

#load in masks

# a1_rev (first auditory area)
a1_mask_file= data_dir + 'masks/a1_rev.nii'
a1_mask = io.load_boolean_mask(a1_mask_file)

# aud_early (early auditory cortex)
aud_mask_file= data_dir + 'masks/aud_early.nii'
aud_mask = io.load_boolean_mask(aud_mask_file)

# whole brain mask
mask_file= data_dir + 'masks/MNI152_T1_3mm_brain_mask.nii'
brain_mask = io.load_boolean_mask(mask_file)

# intersect mask
intersect_mask_file= data_dir + 'masks/intersect_mask.nii.gz'
intersect_mask = io.load_boolean_mask(intersect_mask_file)

# early_visual (early visual cortex)
visual_mask_file= data_dir + 'masks/early_visual.nii'
visual_mask = io.load_boolean_mask(visual_mask_file)

# ddmn_mpfc (medial prefontal cortex)
mpfc_mask_file= data_dir + 'masks/ddmn_mpfc.nii'
mpfc_mask = io.load_boolean_mask(mpfc_mask_file)

# pmc mask (posterior medial cortex)
pmc_mask_file= data_dir + 'masks/pmc_nn.nii'
pmc_mask = io.load_boolean_mask(pmc_mask_file)

# this will be useful for later masking of data
mask_names = ['a1_mask', 'aud_mask', 'brain_mask', 'intersect_mask', 'mpfc_mask', 'pmc_mask', 'visual_mask']
masks = [a1_mask, aud_mask, brain_mask, intersect_mask, mpfc_mask, pmc_mask, visual_mask]


In [4]:
# load in labels
start = df['Start TR']
location = df['Location']
regressors = list(df.columns)
startTR_array = start.values

regressors = ['Space-In/Outdoor', 'valence', 'arousal']

Here we will create arrays of label data for each of the regressors after binarizing the entries in the regressors csv to 1 and 0. We need to make sure that there is a sufficiently large number of TRs with 1 and a large number of TRs with 0.

In [5]:
# load in valence labels
valence = processregressor('valence', startTR_array, df)

i = 0 # initalize counter
while i < valence.shape[0]: 
    
    # + is 1, - is 0
    if valence[i][1] == '+':
        valence[i][1] = 1
    elif valence[i][1] == '-':
        valence[i][1] = 0
    
    # if not yes or no, remove the row entirely
    else: 
        valence = np.delete(valence, i, axis=0)
        i -= 1
    i += 1
valence = remove_duplicate_rows(valence) # remove duplicate rows
valence = upsample_labels(valence, numTRs) # upsample_labels
      
print('Number of + TRs =', (valence[:,1] == 1).sum())
print('Number of - TRs =', (valence[:,1] == 0).sum()) 
print('Total TRs =', valence.shape[0])

Number of + TRs = 1143
Number of - TRs = 276
Total TRs = 1419


In [6]:
# in/outdoor
start = df['Start TR']

inout = processregressor('Space-In/Outdoor', startTR_array, df)

# make labels boolean and remove any extraneous rows 
i = 0 # initalize counter
while i < inout.shape[0]: 
    
    
    # indoor is 1, outdoor is 0
    if inout[i][1] == 'Indoor':
        inout[i][1] = 1
    elif inout[i][1] == 'Outdoor':
        inout[i][1] = 0
    
    # if not indoor or outdoor, remove the row entirely
    else: 
        inout = np.delete(inout, i, axis=0)
        i -= 1

    i += 1
    # print(indoor_outdoor)

inout = remove_duplicate_rows(inout)
inout = upsample_labels(inout, numTRs)
    
# print(np.shape(indoor_outdoor), indoor_outdoor[..., 1])
print('Number of Indoor TRs =',(inout[:,1] == 1).sum())
print('Number of Outdoor TRs =', (inout[:,1] == 0).sum())
print('Total TRs =', inout.shape[0])

Number of Indoor TRs = 992
Number of Outdoor TRs = 427
Total TRs = 1419


In [7]:
# arousal
arousal = processregressor('Arousal', startTR_array, df)

i = 0 # initalize counter
while i < arousal.shape[0]: 
    
    # + is 1, - is 0
    if arousal[i][1] >= 4:
        arousal[i][1] = 1
    elif arousal[i][1] <= 3:
        arousal[i][1] = 0
    
    # if not yes or no, remove the row entirely
    else: 
        arousal = np.delete(arousal, i, axis=0)
        i -= 1
    i += 1
    
arousal = remove_duplicate_rows(arousal) # remove duplicate rows
arousal = upsample_labels(arousal, numTRs) # upsample_labels
      
print('Number of High Arousal TRs =', (arousal[:,1] == 1).sum())
print('Number of Low Arousal TRs =', (arousal[:,1] == 0).sum())
print('Total TRs =', arousal.shape[0])

Number of High Arousal TRs = 873
Number of Low Arousal TRs = 546
Total TRs = 1419


Here we load in, normalize, mask, and save the data to our palmer scratch directory for easy and quick access

In [8]:
p1_dir = data_dir + 'part_1/'
# p1data = [] # add 1 to index to get sub no.
# for i in range(1, 18):
#     p1data.append(nib.load(p1_dir + f'sub-{i:02d}_sherlock_movie_part1.nii'))

# for i in range(len(mask_names)):
#     mask_preprocess_data(p1data, mask_names[i], masks[i], num_subs)

In [9]:
os.listdir('/home/cmhn_ak2776/palmer_scratch/final_project/')

['a1_mask_data.npy',
 'aud_mask_data.npy',
 'brain_mask_data.npy',
 'intersect_mask_data.npy',
 'mpfc_mask_data.npy',
 'pmc_mask_data.npy',
 'visual_mask_data.npy']

In [8]:
# Here we create arrays in this notebook that contain the bold activation for all 17 subjects stored in a 2D array with one dimension being TRs and one dimension being voxel.

def load_maskedData(file_path):
    data = np.load(file_path)
    return np.swapaxes(data, 1, 2)

maskedDataDir = "/home/cmhn_ak2776/palmer_scratch/final_project/"
    
a1_maskedData_normalized = load_maskedData(maskedDataDir + "a1_mask_data.npy")
aud_maskedData_normalized = load_maskedData(maskedDataDir + "aud_mask_data.npy")
brain_maskedData_normalized = load_maskedData(maskedDataDir + "brain_mask_data.npy")
intersect_maskedData_normalized = load_maskedData(maskedDataDir + "intersect_mask_data.npy")
mpfc_maskedData_normalized = load_maskedData(maskedDataDir + "mpfc_mask_data.npy")
pmc_maskedData_normalized = load_maskedData(maskedDataDir + "pmc_mask_data.npy")
visual_maskedData_normalized = load_maskedData(maskedDataDir + "visual_mask_data.npy")

maskedDataNamesList = ['a1_maskedData_normalized', 'aud_maskedData_normalized', 'brain_maskedData_normalized', 'intersect_maskedData_normalized', 'mpfc_maskedData_normalized', 'pmc_maskedData_normalized', 'visual_maskedData_normalized']
maskedDataList = [a1_maskedData_normalized, aud_maskedData_normalized, brain_maskedData_normalized, intersect_maskedData_normalized, mpfc_maskedData_normalized, pmc_maskedData_normalized, visual_maskedData_normalized]

In [11]:
# here you can see the shape of one such variable
a1_maskedData_normalized.shape

(17, 946, 174)

Here we test to see the best mask for every regressor in order to select the mask for the classifier

In [9]:
RegressorList = [inout, valence, arousal]
RegressorNameList = ['inout', 'valence', 'arousal']

In [13]:
# iterate through all masks and all regressors to determine the best mask for each regressor we are trying to classify
for r in range(len(RegressorList)):
    for m in range(len(maskedDataList)):
        
        np.random.seed(0)
        train_data = np.mean(maskedDataList[m][range(16),...], axis = 0) # average over all but the held-out subject, sub 16
        test_data = maskedDataList[m][16,...] # test on the 17th subject
        labels = RegressorList[r][:946, 1].astype('int')

        classifier = SVC(C = 0.01, gamma = 0.01, kernel = 'linear')
        clf = classifier.fit(train_data, labels)

        score = clf.score(test_data, labels)

        print('for Regressor', RegressorNameList[r], 'and mask', maskedDataNamesList[m], 'mean accuracy = ', score) 

for Regressor inout and mask a1_maskedData_normalized mean accuracy =  0.6046511627906976
for Regressor inout and mask aud_maskedData_normalized mean accuracy =  0.5285412262156448
for Regressor inout and mask brain_maskedData_normalized mean accuracy =  0.547568710359408
for Regressor inout and mask intersect_maskedData_normalized mean accuracy =  0.5528541226215645
for Regressor inout and mask mpfc_maskedData_normalized mean accuracy =  0.5200845665961945
for Regressor inout and mask pmc_maskedData_normalized mean accuracy =  0.5813953488372093
for Regressor inout and mask visual_maskedData_normalized mean accuracy =  0.63107822410148
for Regressor valence and mask a1_maskedData_normalized mean accuracy =  0.864693446088795
for Regressor valence and mask aud_maskedData_normalized mean accuracy =  0.7241014799154334
for Regressor valence and mask brain_maskedData_normalized mean accuracy =  0.813953488372093
for Regressor valence and mask intersect_maskedData_normalized mean accuracy 

From this analysis, we can see that:  
  
the best mask for predicting Indoor/Outdoor Scenes is the visual mask with an accuracy of 0.63, with chance being 0.5  
  
the best mask for predicting Valence is tied between a1_maskedData, pmc_maskedData, and visual_maskedData all at accuracy = 0.865  
  
the best mask for predicting Arousal is the whole brain mask with an accuracy of 0.61, with chance being 0.5, however since the accuracy is low and this is a large mask that takes very long to run in a classifier, we can utilize the much smaller early auditory cortex (aud) mask for further optimization, which had an accuracy of 0.591. 

In [14]:
# classifier 1: inout
np.random.seed(0)
train_data = np.mean(visual_maskedData_normalized[range(16),...], axis = 0) # average over all but held-out participant
test_data = visual_maskedData_normalized[16,...] # test on the 17th subject
labels = inout[:946, 1].astype('int')

classifier = SVC(C = 0.01, gamma = 0.01, kernel = 'linear')
clf = classifier.fit(train_data, labels)

inout_score = clf.score(test_data, labels)
    

print('accuracy: ', inout_score)

accuracy:  0.63107822410148


In [15]:
# classifier 2: valence
np.random.seed(0)
train_data = np.mean(pmc_maskedData_normalized[range(16),...], axis = 0) # average over all but held-out participant
test_data = pmc_maskedData_normalized[16,...] # test on the 17th subject
labels = valence[:946, 1].astype('int')

classifier = SVC(C = 0.01, gamma = 0.01, kernel = 'linear')
clf = classifier.fit(train_data, labels)

valence_score = clf.score(test_data, labels)
    

print('accuracy: ', valence_score)

accuracy:  0.864693446088795


In [16]:
# classifier 3: arousal
np.random.seed(0)
train_data = np.mean(aud_maskedData_normalized[range(16),...], axis = 0) # average over all but held-out participant
test_data = aud_maskedData_normalized[16,...]
labels = arousal[:946, 1].astype('int')

classifier = SVC(C = 0.01, gamma = 0.01, kernel = 'linear')
clf = classifier.fit(train_data, labels)

arousal_score = clf.score(test_data, labels)
    

print('accuracy: ', np.mean(arousal_score)) 

accuracy:  0.5919661733615222


This accuracy is too low. Let's try to improve it using a grid search for best classifier params and a select k best features.

In [17]:
# arousal optimization
np.random.seed(0)
train_data = np.mean(aud_maskedData_normalized[range(16),...], axis = 0) # average over all but held-out participant
test_data = aud_maskedData_normalized[16,...]
labels = arousal[:946, 1].astype('int')

for k in range(40, 400, 40):
    # Feature selection
    k = k
    selector = SelectKBest(f_classif, k=k)
    train_data_selected = selector.fit_transform(train_data, labels)
    test_data_selected = selector.transform(test_data)

    # Hyperparameter tuning with GridSearchCV
    param_grid = {
        'C': [0.001, 0.01, 0.1],
        'gamma': [0.001, 0.01, 0.1],
        'kernel': ['linear', 'rbf']
    }

    grid_search = GridSearchCV(SVC(), param_grid, cv=5)
    grid_search.fit(train_data_selected, labels)

    # Train the classifier with the best parameters
    best_classifier = grid_search.best_estimator_
    best_classifier.fit(train_data_selected, labels)

    # Test the classifier
    arousal_score = best_classifier.score(test_data_selected, labels)

    print('accuracy: ', np.mean(arousal_score), 'k =', k, 'params =', grid_search.best_params_)

accuracy:  0.5655391120507399 k = 40 params = {'C': 0.1, 'gamma': 0.001, 'kernel': 'linear'}
accuracy:  0.620507399577167 k = 80 params = {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}
accuracy:  0.5158562367864693 k = 120 params = {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}
accuracy:  0.5126849894291755 k = 160 params = {'C': 0.1, 'gamma': 0.1, 'kernel': 'rbf'}
accuracy:  0.6247357293868921 k = 200 params = {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
accuracy:  0.6236786469344608 k = 240 params = {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
accuracy:  0.635306553911205 k = 280 params = {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
accuracy:  0.6004228329809725 k = 320 params = {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}
accuracy:  0.5771670190274841 k = 360 params = {'C': 0.1, 'gamma': 0.01, 'kernel': 'rbf'}


Here, utilizing GridSearchCV and SelectKBest, we were able to determine that selecting for the k = 280 best features and with the classifier parameters set to C = 0.1, gamma = 0.01, and kernel = 'rbf', the arousal classifier accuracy improved from 0.591 to 0.635.

This is just an exploratory analysis of whether arousal can predict the location in the first part of the data as the outdoor scenes here contain a high arousal war scene

In [19]:
# Exploratory NOT FOR GRADING: uses arousal to predict indoor/outdoor

arousaltest = df['Arousal']

# To turn the column into a vector of values:
print(arousaltest.values[:10])

loc = df['Space-In/Outdoor']

# To turn the column into a vector of values:
print(loc.values[:10]) # Just show the first 10 values.

from sklearn.svm import LinearSVC

X_test = arousaltest.values[:200].reshape(-1,1)
y_test = loc.values[:200].reshape(-1,1)
X_train = arousaltest.values[200:400].reshape(-1,1)
y_train = loc.values[200:400].reshape(-1,1)

# Create a linear SVC model with hyperparameter C set to 1.  
model = LinearSVC(C=1)

# Fit the model on the BOLD data and corresponding stimulus labels.
model.fit(X_train, y_train)

# Score your model on the test data.
score = model.score(X_test, y_test)
print(f'Accuracy = {score}')

[3. 3. 3. 3. 3. 4. 4. 5. 5. 5.]
['Indoor' 'Indoor' 'Indoor' 'Indoor' 'Indoor' 'Indoor' 'Indoor' 'Outdoor'
 'Outdoor' 'Outdoor']
Accuracy = 0.695


/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## 2. Mystery Segment Matching

For participants 2 through 17, you are given the first 300 TRs (450s) of continuous data from viewing part 2 of the movie. For participant 1, you have just a mystery segment: a 30-TR (45s) chunk pulled from those same 300 TRs of the movie. Your goal is to figure out _when_ in those first 300 TRs your mystery segment begins, based on the data from all of the _other_ participants. Your answer will be the starting TR of the 30-TR mystery segment, which is some timepoint between 1 and 270. 

**Data directory:** Data can be found in `/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/`. Remember, participant 1 is a volume of 30 TRs, and all other participants are volumes of 300 TRs.

### Report the starting TR of the mystery epoch.
Justify your response with supporting evidence.

**Answer:**  121 (but maybe 128) (note there is another copy of this next to the last code chunk that makes it easier to see the reasoning)
  
Looking at the results from the last code chunk, it seems the start TR is somewhere between 121 and 128. The huge difference in measures of center for both auditory masks might be due to some sort of noise that is unaccounted for such as a particularly loud noise from the MRI machine at a certain TR that causes all subs to synchronize in auditory activity and thus makes them both undesirable for this analysis.  
  
The visual mask had the same median and mode, which is promising and the high mean might be due to outliers that caused synchronised visual stimulation at a time that is irrelevant to our analysis from something other than the sherlock data. The pmc and mpfc masks give somewhat promising data and the mean for these is unlikely to be induced by outliers as simple as loud noises or visual stimulation and thus capturing attention and emotion and memories in synchrony is likely not influenced by outlier occurances at random times.  
  
In order to give a single answer, I will state that my predicted TR is 121 as it was both the median and mode of the visual mask and falls nicely between the TR predictions. (it might still be 128)

### Include your code below
Please make sure that your code is commented. If you performed analyses outside of this notebook (e.g., in a python script that needed more computational resources) please note that here and be sure to upload any accompanying notebook(s) or script(s) (submissions without accompanying code will be given zero points).

In [10]:
import numpy as np
import nibabel as nib
from scipy.signal import correlate

In [11]:
pt2_dir = data_dir + 'mystery_segments_q2/'
print(os.listdir(pt2_dir))

['sub-12_segment_q2.nii', 'sub-17_segment_q2.nii', 'sub-06_segment_q2.nii', 'sub-11_segment_q2.nii', 'sub-03_segment_q2.nii', 'sub-09_segment_q2.nii', 'sub-04_segment_q2.nii', 'sub-16_segment_q2.nii', 'sub-05_segment_q2.nii', 'sub-14_segment_q2.nii', 'sub-07_segment_q2.nii', 'sub-10_segment_q2.nii', 'sub-08_segment_q2.nii', 'sub-13_segment_q2.nii', 'sub-02_segment_q2.nii', 'sub-01_segment_q2.nii', 'sub-15_segment_q2.nii']


In [12]:
p2files = [pt2_dir + 'sub-12_segment_q2.nii', pt2_dir + 'sub-17_segment_q2.nii', pt2_dir + 'sub-06_segment_q2.nii', pt2_dir + 'sub-11_segment_q2.nii', pt2_dir + 'sub-03_segment_q2.nii', pt2_dir + 'sub-09_segment_q2.nii', pt2_dir+'sub-04_segment_q2.nii', pt2_dir+'sub-16_segment_q2.nii', pt2_dir+'sub-05_segment_q2.nii', pt2_dir+'sub-14_segment_q2.nii', pt2_dir+'sub-07_segment_q2.nii', pt2_dir+'sub-10_segment_q2.nii', pt2_dir+'sub-08_segment_q2.nii', pt2_dir+'sub-13_segment_q2.nii', pt2_dir+'sub-02_segment_q2.nii', pt2_dir+'sub-01_segment_q2.nii', pt2_dir+'sub-15_segment_q2.nii']
subjects_data = [nib.load(file).get_fdata() for file in p2files]

In [15]:
p2files

['/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-12_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-17_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-06_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-11_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-03_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-09_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-04_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-16_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-05_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-14_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed

In [15]:
sub_01_data = subjects_data[15]
rest_subjects_data = np.stack(subjects_data[:15] + [subjects_data[16]], axis=0)

In [20]:
sub_01_data.shape

(61, 73, 61, 30)

In [22]:
rest_subjects_data.shape

(16, 61, 73, 61, 300)

Note: I could not find out how to properly apply the time segment matching function from pset 11 or properly figure out using correlations to determine similarities and thus found an approach using mean squared error with a slightly different application strategy. This will likely have flaws but seemed logical.

In [45]:
def mse(segment_1, segment_2):
    """
    Calculate the mean squared error between two time series (segments).

    Params:
    segment_1 (numpy.ndarray): The first time series (1D array).
    segment_2 (numpy.ndarray): The second time series (1D array) of the same length as the first one.

    Returns:
    float: The mean squared error between the two time series.
    """
    return np.mean((segment_1 - segment_2) ** 2)

def time_segment_matching(sub_01_ts, subject_ts):
    """
    Find the best matching time segment in a longer time series for a given shorter time series.

    Params:
    sub_01_ts (numpy.ndarray): The shorter time series (1D array).
    subject_ts (numpy.ndarray): The longer time series (1D array) to search for the best matching segment.

    Returns:
    int: The starting index of the best matching time segment in the longer time series.
    """
    num = len(subject_ts) - len(sub_01_ts) + 1
    mse_values = np.zeros(num)

    for TR in range(num):
        mse_values[TR] = mse(sub_01_ts, subject_ts[TR:TR + len(sub_01_ts)])

    best_TR = np.argmin(mse_values)
    return best_TR

In [94]:
MaskList = [a1_mask, aud_mask, visual_mask, pmc_mask, mpfc_mask]
MaskNames = ['a1_mask', 'aud_mask', 'visual_mask','pmc_mask', 'mpfc_mask']
for m in range(len(MaskList)):
    # Get the dimensions of the sub-01 data (x_dim, y_dim, and z_dim for the brain voxels)
    x_dim, y_dim, z_dim, _ = sub_01_data.shape

    # Set the length of the time segment to compare
    segment_length = 30

    # Get the indices of the brain voxels within the masks
    brain_voxels = np.argwhere(MaskList[m])

    # Initialize the best_timepoints array with -1 to indicate unused voxels. This array will store the best matching time point (BTR) for each voxel within the mask
    best_timepoints = np.full((x_dim, y_dim, z_dim), -1, dtype=int)

    other_subjects_data = np.mean(rest_subjects_data, axis = 0)
    
    # Loop through each voxel within the visual_mask
    for x, y, z in brain_voxels:
        # Initialize the minimum mean squared error (MSE) to a large value
        min_mse = float('inf')
        best_BTR = 0

        # Extract the time series for the current voxel in sub-01 for the specified segment_length
        sub_01_ts = sub_01_data[x, y, z, :]
        
        subjects_ts = other_subjects_data[x, y, z, :]

        # Find the best matching time point (BTR) for the current subject using the time_segment_matching function
        BTR = time_segment_matching(sub_01_ts, subjects_ts)

        # Calculate the mean squared error for the best matching time segment in the current subject
        current_mse = mse(sub_01_ts, subjects_ts[BTR:BTR + segment_length])

        # If the current mean squared error is smaller than the minimum mean squared error found so far, update the minimum mean squared error and the best BTR
        if current_mse < min_mse:
            min_mse = current_mse
            best_BTR = BTR

        # Store the best matching time point (BTR) for the current voxel in the best_timepoints array
        best_timepoints[x, y, z] = best_BTR

    from scipy.stats import mode

    # Get the best timepoints for the voxels within the aud_mask
    best_timepoints_masked = best_timepoints[MaskList[m]]
    
    # Calculate the mode of the best_timepoints_masked
    location_mode, count = mode(best_timepoints_masked)

    print(f"The most likely Starting TR of the 30 TRs in the 300 TRs is at TR: {location_mode[0]} according to {MaskNames[m]}")
    print(f"The average of best_timepoints_masked was {np.mean(best_timepoints_masked)}")
    print(f"The median was {np.median(best_timepoints_masked)}")

The most likely Starting TR of the 30 TRs in the 300 TRs is at TR: 49 according to a1_mask
The average of best_timepoints_masked was 69.91379310344827
The median was 49.0
The most likely Starting TR of the 30 TRs in the 300 TRs is at TR: 145 according to aud_mask
The average of best_timepoints_masked was 91.23673870333988
The median was 78.0
The most likely Starting TR of the 30 TRs in the 300 TRs is at TR: 121 according to visual_mask
The average of best_timepoints_masked was 144.8827361563518
The median was 121.0
The most likely Starting TR of the 30 TRs in the 300 TRs is at TR: 112 according to pmc_mask
The average of best_timepoints_masked was 128.9085239085239
The median was 130.0
The most likely Starting TR of the 30 TRs in the 300 TRs is at TR: 128 according to mpfc_mask
The average of best_timepoints_masked was 122.26028169014084
The median was 129.0


**Answer:**  121 (but maybe 128) (note there is another copy of this next to the last code chunk that makes it easier to see the reasoning)
  
Looking at the results from the last code chunk, it seems the start TR is somewhere between 121 and 128. The huge difference in measures of center for both auditory masks might be due to some sort of noise that is unaccounted for such as a particularly loud noise from the MRI machine and thus makes them both undesirable for this analysis.  
  
The visual mask had the same median and mode, which is promising and the high mean might be due to outliers that caused synchronised visual stimulation at a time that is irrelevant to our analysis from something other than the sherlock data. The pmc and mpfc masks give somewhat promising data and the mean for these is unlikely to be induced by outliers as simple as loud noises or visual stimulation and thus capturing attention and emotion and memories in synchrony is likely not influenced by outlier occurances at random times.  
  
In order to give a single answer, I will state that my predicted TR is 121 as it was both the median and mode of the visual mask and falls nicely between the TR predictions. (it might still be 128)

## 3. Mystery Segment Decoding

You will be given a mystery segment of 100 TRs from all participants in Part 2 of the movie. All participants' volumes are for the same 100 TRs, and you must figure out when in the movie this epoch occurred. Note that this segment does not overlap with the 300 TRs used in Question 2 - that means the starting TR could be between TRs 301 and 930. To determine the location of the mystery segment, use the classifiers you developed in Question 1 to make predictions about regressors for the mystery segment. Then, identify the location of the mystery segment by comparing the predicted regressors to the actual regressors for Part 2 (provided in the regressors file) and seeing what position of the mystery segment yields the best match between predicted and actual regressors. You need to provide code that does this matching and also quantitative results that justify your choice of mystery segment location. 

Again, please do not directly share your guess about the mystery segment with other students (it’s fine to share your ideas about analysis approaches with other students, but don’t share the final answer).

**Data directory:** Data can be found in `/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q3/`.


### Report the starting TR of the mystery epoch.
Justify your response with supporting evidence.

**Answer:** 404; the start TR for which our SVC models' predictions of regressor values were most accurate for the following 100 TRs was selected to be 404.

### Include your code below
Please make sure that your code is commented. If you performed analyses outside of this notebook (e.g., in a python script that needed more computational resources) please note that here and be sure to upload any accompanying notebook(s) or script(s) (submissions without accompanying code will be given zero points).

In [35]:
subjects_data_q3

In [95]:
# Set the directory path for the mystery_segments_q3 folder
mystery_segments_folder = data_dir + 'mystery_segments_q3/'

# Print the list of files in the mystery_segments_folder
print(os.listdir(mystery_segments_folder))

# Initialize an empty list to store the subject data
subjects_data_q3 = []

# Load the NIfTI images for subjects 1 to 17 and append them to subjects_data_q3
for i in range(1, 18):
    nifti_image = nib.load(mystery_segments_folder + f'sub-{i:02d}_segment_q3.nii')
    subjects_data_q3.append(nifti_image)

# Define a function to mask and preprocess data for all subjects
def mask_scale_q3(data, mask, num_subs):
    """Mask and preprocess data for all subjects.

    Params:
    data: 4D fMRI data
    mask: boolean mask
    num_subs: number of subjects
    
    Returns:
    all_subject_data: array of all the bold data for the mask chosen for all subs
    """
    all_subject_data = []
    for subject in range(num_subs):
        masked_data = image.mask_image(data[subject], mask)
        scaler = preprocessing.StandardScaler().fit(masked_data)
        preprocessed_data = scaler.transform(masked_data)
        all_subject_data.append(np.swapaxes(preprocessed_data, 0, 1))
    return all_subject_data
        
# Set the visual mask
visual_mask = visual_mask

# Extract and preprocess the visual data for all subjects
extracted_visual_data = mask_scale_q3(subjects_data_q3, visual_mask, len(subjects_data_q3))

# Compute the mean of the extracted_visual_data across subjects
avg_visual_segment = np.mean(extracted_visual_data, axis = 0)

# Print the shape of the average visual segment
print(np.shape(avg_visual_segment))

# Set the audio mask
audio_mask = aud_mask

# Extract and preprocess the audio data for all subjects
extracted_audio_data = mask_scale_q3(subjects_data_q3, audio_mask, len(subjects_data_q3))

# Compute the mean of the extracted_audio_data across subjects
avg_audio_segment = np.mean(extracted_audio_data, axis = 0)

# Print the shape of the average audio segment
print(np.shape(avg_audio_segment))

# Set the PMC mask
pmc_mask = pmc_mask

# Extract and preprocess the PMC data for all subjects
extracted_pmc_data = mask_scale_q3(subjects_data_q3, pmc_mask, len(subjects_data_q3))

# Compute the mean of the extracted_pmc_data across subjects
avg_pmc_segment = np.mean(extracted_pmc_data, axis = 0)

# Print the shape of the average PMC segment
print(np.shape(avg_pmc_segment))

['sub-06_segment_q3.nii', 'sub-04_segment_q3.nii', 'sub-09_segment_q3.nii', 'sub-07_segment_q3.nii', 'sub-14_segment_q3.nii', 'sub-13_segment_q3.nii', 'sub-10_segment_q3.nii', 'sub-12_segment_q3.nii', 'sub-11_segment_q3.nii', 'sub-02_segment_q3.nii', 'sub-05_segment_q3.nii', 'segment_q3_part2.nii', 'sub-17_segment_q3.nii', 'sub-03_segment_q3.nii', 'sub-08_segment_q3.nii', 'sub-01_segment_q3.nii', 'sub-16_segment_q3.nii', 'sub-15_segment_q3.nii']
(100, 307)
(100, 1018)
(100, 481)


Here we create SVCs to create predictions for the indoor/outdoor value, valence, and arousal for each TR in the mystery 100 TR segment so that we can determine where in the 301 - 930 TRs the 100 TRs fit 

In [96]:
# Use a SVC to predict inout from the average visual segment
visual_data = np.mean(visual_maskedData_normalized, axis=0)
inout_labels = inout[:946, 1].astype('int')
linear_svm = SVC(C=0.01, gamma=0.01, kernel='linear')
clf = linear_svm.fit(visual_data, inout_labels)
inout_pred = clf.predict(avg_visual_segment)

# Use a SVC to predict valence from the average PMC segment
pmc_data = np.mean(pmc_maskedData_normalized, axis=0)
valence_labels = valence[:946, 1].astype('int')
clf = SVC(C=0.01, gamma=0.01, kernel='linear')
classifier = clf.fit(pmc_data, valence_labels)
valence_pred = classifier.predict(avg_pmc_segment)

# Use a SVC to predict arousal from the average audio segment
audio_data = np.mean(aud_maskedData_normalized, axis=0)
arousal_labels = arousal[:946, 1].astype('int')
clf = SVC(C=0.01, gamma=0.001, kernel='rbf')
classifier = clf.fit(audio_data, arousal_labels)
arousal_pred = classifier.predict(avg_audio_segment)

# Combine the predictions from the three classifiers
timepointwise_predictions = np.vstack((inout_pred, valence_pred, arousal_pred)).T

# Print the shape of the combined predictions
print(np.shape(timepointwise_predictions))


(100, 3)


Here we load in the actual inout, valence, and arousal values for the TRs after 300 until the end. We then compare the classifiers' predicted values for inout, valence, and arousal from the 100 TR segment to the actualy inout, valence, and arousal at every potential start TR between 301 and 930 to see where we have the best match by getting the maximum of the set of all match accuracies between the classifier's predictions and the actual TRs between 301 and 930.

In [101]:
# Stack the actual TR values for inout, valence, and arousal
actual_TR_values = np.vstack((inout[..., 1], valence[..., 1], arousal[..., 1])).T[301:]

# Define a function to calculate the accuracy for a given TR range
def calculate_accuracy_for_range(start_TR, predictions, actual_values):
    correct_predictions = sum(1 for j in range(100) if all(predictions[j] == actual_values[start_TR + j]))
    return correct_predictions / 100

# Calculate accuracies for each possible TR in the range of 301 to 930
accuracies = [calculate_accuracy_for_range(i, timepointwise_predictions, actual_TR_values) for i in range(930 - 301)]

# Find the most likely TR by adding 301 to the index of the maximum accuracy
StartTR = accuracies.index(max(accuracies)) + 301
print('Start TR is:', StartTR)

Start TR is: 404


## 4. Mystery Subjects 

You will be given a segment of 600 TRs from all participants in Part 2, but where the participant names have been scrambled. The time points and voxel orders are consistent across participants. The participants are named from A-Q and you must make your best guess as to the corresponding participant numbers. To help you with this, some participant labels have already been assigned.  

This question is hard conceptually, but you have all of the tools you need. SRM will be useful but you are welcome to take any valid approach from class. Note that SRM is probabilistic so we highly suggest using a random seed. If you can accurately match the mystery subject labels for A and Q (the subjects we number below) then your analysis is probably on the right track. If you can get at least 4 other mystery subject labels correct (6/17 total), you will receive full credit for the answer component of the grade.  

**Data directory:** The data can be found in: `/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/`  

### Report the mystery subject labels 
Explain how you got to this answer and note if you are only confident on a few subjects, explaining why this may be.

**A:** 6         
**B:**   
**C:**   
**D:**  
**E:**  
**F:**  
**G:**  
**H:**  
**I:**     
**J:**   
**K:**  
**L:**  
**M:**    
**N:**  
**O:**     
**P:**  
**Q:** 4 

### Include your code below
Please make sure that your code is commented. If you performed analyses outside of this notebook (e.g., in a python script that needed more computational resources) please note that here and be sure to upload any accompanying notebook(s) or script(s) (submissions without accompanying code will be given zero points).

### None of my approaches worked but here is what I had thus far:

In [13]:
pt4_dir = data_dir + 'mystery_subjects_q4/'
print(os.listdir(pt4_dir))

['sherlock_movie_Q.nii.gz', 'sherlock_movie_A.nii.gz', 'sherlock_movie_F.nii.gz', 'sherlock_movie_G.nii.gz', 'sherlock_movie_K.nii.gz', 'sherlock_movie_P.nii.gz', 'sherlock_movie_O.nii.gz', 'sherlock_movie_M.nii.gz', 'sherlock_movie_J.nii.gz', 'sherlock_movie_E.nii.gz', 'sherlock_movie_L.nii.gz', 'sherlock_movie_D.nii.gz', 'sherlock_movie_I.nii.gz', 'sherlock_movie_C.nii.gz', 'sherlock_movie_H.nii.gz', 'sherlock_movie_B.nii.gz', 'sherlock_movie_N.nii.gz']


In [ ]:
subject_ids = ['Q', 'A', 'F', 'G', 'K', 'P', 'O', 'M', 'J', 'E', 'L', 'D', 'I', 'C', 'H', 'B','N']

p4files = [f"{pt4_dir}sherlock_movie_{subject_id}.nii.gz" for subject_id in subject_ids]

In [19]:
p4files

['/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_Q.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_A.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_F.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_G.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_K.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_P.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_O.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_M.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_J.nii.gz',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_subjects_q4/sherlock_movie_E.nii.gz',
 '/gpfs/gibbs/project/cmhn/dat

In [84]:
p2files

['/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-12_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-17_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-06_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-11_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-03_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-09_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-04_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-16_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-05_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-14_segment_q2.nii',
 '/gpfs/gibbs/project/cmhn/data/Sherlock_processed

In [57]:
def mask_preprocess_data(data, mask, num_subs):
    """Mask and preprocess data for all subjects.

    Params:
    data: 4D fMRI data
    mask: boolean mask
    num_subs: number of subjects

    Returns:
    all_subject_data
    """
    all_subject_data = []
    for subject in range(num_subs):
        masked_data = image.mask_image(data[subject], mask)
        scaler = preprocessing.StandardScaler().fit(masked_data)
        preprocessed_data = scaler.transform(masked_data)
        all_subject_data.append(preprocessed_data)
    return all_subject_data

In [61]:
import numpy as np
from brainiak.funcalign import srm
from sklearn.model_selection import KFold

subjects_data_q2 = []
subjects_data_q4 = []

# Load the NIfTI images for subjects 1 to 17 and append them to subjects_data
for i in range(1, 18):
    nifti_image = nib.load(f'/gpfs/gibbs/project/cmhn/data/Sherlock_processed/mystery_segments_q2/sub-{i:02d}_segment_q2.nii')
    subjects_data_q2.append(nifti_image)

print(1)

subject_ids = ['Q', 'A', 'F', 'G', 'K', 'P', 'O', 'M', 'J', 'E', 'L', 'D', 'I', 'C', 'H', 'B','N']
for subject_id in subject_ids:
    nifti_image = nib.load(f"{pt4_dir}sherlock_movie_{subject_id}.nii.gz")
    subjects_data_q4.append(nifti_image)

print(2)

1
2


In [65]:
# Preprocess data
p4_data_preprocessed = mask_preprocess_data(subjects_data_q4, visual_mask, 17)
p2_data_preprocessed = mask_preprocess_data(subjects_data_q2, visual_mask, 17)

In [83]:
np.shape(p4_data_preprocessed)

(17, 307, 600)

In [67]:
Q_data_preprocessed = p4_data_preprocessed[0]

In [86]:
# Set up cross-validation
kf = KFold(n_splits=5, shuffle=True, random_state=42)
print(1)
max_correlation = 0
subject_index = -1

for i in range(1, 18):
    if i == 16:  # Skip the 16th subject (sub1 with 30 TRs)
        continue

    correlations = []

    for train_indices, test_indices in kf.split(p2_data_preprocessed[i - 1]):
        # Train SRM on the training set
        srm_model = srm.SRM(n_iter=10, features=50)
        train_data = [p2_data_preprocessed[sub_idx][train_indices] for sub_idx in range(17) if sub_idx != i-1 and sub_idx != 15]
        srm_model.fit(train_data)
        print(2)

        # Transform Q_data and the test set of the current subject using the trained SRM
        p4_shared = srm_model.transform([p4_data_preprocessed])[0]


print(f"Q is most likely subject {subject_index}")

1
2


ValueError: The number of subjects does not match the one in the model.

### Below are a few prior erroneous approaches that also didn't work.

In [35]:
import numpy as np
import nibabel as nib

def load_nii_data(filepath):
    nii = nib.load(filepath)
    return np.array(nii.dataobj)

def calculate_mean_correlation(data1, data2):
    if data1.shape != data2.shape:
        raise ValueError("The dimensions of the data arrays do not match.")
    
    data1_normalized = (data1 - data1.mean(axis=-1, keepdims=True)) / data1.std(axis=-1, keepdims=True)
    data2_normalized = (data2 - data2.mean(axis=-1, keepdims=True)) / data2.std(axis=-1, keepdims=True)
    correlations = np.nanmean(data1_normalized * data2_normalized, axis=-1)

    return np.nanmean(correlations)

Q_data = load_nii_data(Qfile)[:,:,:,:300]  # Load first 300 TRs of Qfile
max_correlation = 0
subject_index = -1

for i in range(1, 18):  # Change the loop range to include the 17th subject
    if i == 16:  # Skip the 16th subject
        continue
    p2file = p2files[i-1]  # Get the file path for the current subject
    p2_data = load_nii_data(p2file)
    correlation = calculate_mean_correlation(Q_data, p2_data)

    if correlation > max_correlation:
        max_correlation = correlation
        subject_index = i

print(f"Q is most likely subject {subject_index} (excluding subject 16).")

/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == "":
/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]
/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: Mean of empty slice
  


Q is most likely subject 14 (excluding subject 16).


In [37]:
import numpy as np
import nibabel as nib

A_data = load_nii_data(Afile)[:,:,:,:300]  # Load first 300 TRs of Qfile
max_correlation = 0
subject_index = -1

for i in range(1, 18):  # Change the loop range to include the 17th subject
    if i == 16:  # Skip the 16th subject
        continue
    p2file = p2files[i-1]  # Get the file path for the current subject
    p2_data = load_nii_data(p2file)
    correlation = calculate_mean_correlation(Q_data, p2_data)

    if correlation > max_correlation:
        max_correlation = correlation
        subject_index = i

print(f"A is most likely subject {subject_index} (excluding subject 16).")

/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: invalid value encountered in true_divide
  if sys.path[0] == "":
/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]
/gpfs/gibbs/project/cmhn/share/conda_envs/mybrainiak/lib/python3.7/site-packages/ipykernel_launcher.py:14: RuntimeWarning: Mean of empty slice
  


A is most likely subject 14 (excluding subject 16).


# Help

This section contains helper functions and hints that you could use to solve the questions.

**Reading excel files.**
Pandas provides a nice interface to load excel files into dataframes.

In [ ]:
import pandas as pd
data_dir ='/gpfs/gibbs/project/cmhn/data/Sherlock_processed/'
df = pd.read_csv(data_dir + 'regressor_file.csv') # pandas plays best with csv files
df.head()

**Extracting a column**
To extract a column of values from a dataframe, the following sample code is provided. 

Be careful of any leading or trailing spaces in the column titles.

In [ ]:
start= df['Start TR']
print(start[:10]) # Just show the first 10 rows.

# To turn the column into a vector of values:
print(start.values[:10]) # Just show the first 10 values.

*Note: Start TR jumps from TR 0 to TR 8 -- meaning, the regressors don't have one row for every TR, like we've seen for other datasets. You need to handle this to properly train your classifiers!*

**Masking data:** You will find that extracting data from a mask takes time and is memory intensive; repeating that process is unnecessary. You can apply the given masks to your data and save the masked numpy arrays in a directory in `~/palmer_scratch` if you prefer, then load that data back in whenever you want to use it.

**Helper functions:** We provided many functions in `utils.py` that help with data loading and normalization. Use them. Feel free to create your own `final_project_utils.py` with any paths, functions, etc. that you create and reuse for this project. Upload that along with this notebook.

In [ ]:
%matplotlib inline
from brainiak import image, io
from scipy.stats import stats
import nibabel as nib
import numpy as np
from matplotlib import pyplot as plt

In [ ]:
# Load in the PMC mask
from brainiak import image, io
data_dir = '/gpfs/gibbs/project/cmhn/data/Sherlock_processed/'
mask_file= data_dir + 'masks/pmc_nn.nii'
pmc_mask = io.load_boolean_mask(mask_file)
plt.imshow(pmc_mask[:,:,30]) #30th Z slice

In [ ]:
# Load in the whole brain mask
mask_file= data_dir + 'masks/MNI152_T1_3mm_brain_mask.nii'
brain_mask = io.load_boolean_mask(mask_file)
plt.imshow(brain_mask[:,:,30]) #30th Z slice

In [ ]:
# Load in the intersect mask -- where all subjects have the same voxels present
mask_file= data_dir + 'masks/intersect_mask.nii.gz'
intersect_mask = io.load_boolean_mask(mask_file)
plt.imshow(intersect_mask[:,:,30]) #30th Z slice
